<a href="https://colab.research.google.com/github/mohammad2682/FVS-SVM-RKHS/blob/main/SVM_RKHS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from sklearn import svm

In [2]:
!git clone https://github.com/mohammad2682/FVS-SVM-RKHS

Cloning into 'FVS-SVM-RKHS'...
remote: Enumerating objects: 50, done.
remote: Counting objects: 100% (50/50), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 50 (delta 19), reused 41 (delta 17), pack-reused 0
Unpacking objects: 100% (50/50), done.


In [22]:
def sigma(distance):
  return 0.1 * np.linalg.norm(dist)

In [55]:
def K(FV1, FV2):
  dist = abs(FV1.values-FV2.values)
  sig = sigma(dist)
  return np.exp(-1*np.square(dist)/(2*sig))

In [3]:
df = pd.read_csv("FVS-SVM-RKHS/datasets/pima.csv")
df.head()

preg  plas  pres  skin  insu  mass   pedi  age            class
0    14   175    62    30     0  33.6  0.212   38  tested_positive
1     4   146    78     0     0  38.5  0.520   67  tested_positive
2    15   136    70    32   110  37.1  0.153   43  tested_positive
3     3   107    62    13    48  22.9  0.678   23  tested_positive
4     3   169    74    19   125  29.9  0.268   31  tested_positive

In [56]:
FV1 = df.iloc[[0], :-1]
FV2 = df.iloc[[1], :-1]
k = K(FV1, FV2)

In [58]:
LF = abs(1-(np.transpose(k)*k[::-1]*k)/k)

In [93]:
np.dot(np.dot(k[::-1], k.T), k)

array([[2.04213510e-04, 5.56498434e-34, 1.21886002e-10, 2.46300800e-36,
        1.99485714e+00, 2.19762840e-01, 1.97754735e+00, 5.56498434e-34]])

In [89]:
k/k

array([[1., 1., 1., 1., 1., 1., 1., 1.]])

In [47]:
k.T

array([1.02369992e-04, 2.78966560e-34, 6.11001157e-11, 1.23467889e-36,
       1.00000000e+00, 1.10164700e-01, 9.91322789e-01, 2.78966560e-34])

In [ ]:
df['class'].unique()

array(['tested_positive', 'tested_negative'], dtype=object)

In [26]:
df.groupby("class").agg("count")

preg  plas  pres  skin  insu  mass  pedi  age
class                                                         
tested_negative   500   500   500   500   500   500   500  500
tested_positive   268   268   268   268   268   268   268  268