<a href="https://colab.research.google.com/github/mohammad2682/FVS-SVM-RKHS/blob/main/SVM_RKHS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from sklearn import svm

In [2]:
!git clone https://github.com/mohammad2682/FVS-SVM-RKHS

Cloning into 'FVS-SVM-RKHS'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 65 (delta 24), reused 41 (delta 17), pack-reused 0
Unpacking objects: 100% (65/65), done.


In [3]:
def sigma(df):
  N = df.shape[0]
  sigma = []
  for i in range(N):
    for j in range(i+1, N):
      x_i = df.iloc[[i], :-1]
      x_j = df.iloc[[j], :-1]
      sigma.append(np.linalg.norm(x_i.values - x_j.values))
  return 0.1 * np.max(sigma)

In [38]:
def K(FV1, FV2, sigma):
  dist = np.linalg.norm(FV1-FV2)
  return np.exp(-1*np.square(dist)/(2*sigma))

In [48]:
FV1

array([[ 14, 175]])

In [52]:
FV1 - vec

array([[13, -6]])

In [54]:
np.square(np.linalg.norm(FV1-vec))

205.0

In [57]:
np.exp(-1 * 205/2)

3.0536243137246927e-45

In [5]:
df = pd.read_csv("FVS-SVM-RKHS/datasets/pima.csv")
df.head()

preg  plas  pres  skin  insu  mass   pedi  age            class
0    14   175    62    30     0  33.6  0.212   38  tested_positive
1     4   146    78     0     0  38.5  0.520   67  tested_positive
2    15   136    70    32   110  37.1  0.153   43  tested_positive
3     3   107    62    13    48  22.9  0.678   23  tested_positive
4     3   169    74    19   125  29.9  0.268   31  tested_positive

In [6]:
df_test1 = df.iloc[:3, :]
df_test2 = df.iloc[-7:, :]
df_test = pd.concat([df_test1, df_test2]).reset_index(drop=True)
df_test = df_test[["preg", "plas", "class"]]

In [7]:
df_test

preg  plas            class
0    14   175  tested_positive
1     4   146  tested_positive
2    15   136  tested_positive
3     6   114  tested_negative
4     6    92  tested_negative
5     5   117  tested_negative
6     4    83  tested_negative
7     7   119  tested_negative
8     1    95  tested_negative
9     1   181  tested_positive

In [8]:
sig = sigma(df_test)

In [9]:
FV1 = df_test.iloc[[0], :-1]
FV2 = df_test.iloc[[1], :-1]
FV3 = df_test.iloc[[2], :-1]
k1 = K(FV1, FV2, sigma = sig)

In [28]:
LF = abs(1-(np.transpose(KS)/KS*KS))

In [47]:
sig

9.804590761474953

In [46]:
FV1 = df_test.iloc[[0], :-1].values
tau = 0.001
KS = [FV1]
for vec in df_test.iloc[1:, :-1].values:
  k = K(FV1, vec, sigma = sig)
  LF = abs(1-k)
  if LF > tau:
    KS.append(vec)

1.442766546342933e-21
1.9565663937797177e-34
1.4848637713833032e-84
1.0194946300447523e-154
5.033139142377933e-77
2.131824375092986e-190
2.8852982683477277e-71
3.258573858165986e-146
2.882445455101146e-05


In [58]:
KS

array(1.44276655e-21)

In [59]:
KS.append(np.array(10))

AttributeError: ignored

In [44]:
LF

0.999971175545449

In [30]:
np.linalg.inv(KS)

LinAlgError: ignored

In [ ]:
k.T

array([1.02369992e-04, 2.78966560e-34, 6.11001157e-11, 1.23467889e-36,
       1.00000000e+00, 1.10164700e-01, 9.91322789e-01, 2.78966560e-34])

In [ ]:
df['class'].unique()

array(['tested_positive', 'tested_negative'], dtype=object)

In [ ]:
df.groupby("class").agg("count")

preg  plas  pres  skin  insu  mass  pedi  age
class                                                         
tested_negative   500   500   500   500   500   500   500  500
tested_positive   268   268   268   268   268   268   268  268